### ISSUE TITLE
Add an accountName field to the Account data type

### ISSUE THREAD

**Issue by GetContented** [rwobben/paytime#10]
This should be relatively easy to do. The only slight adjustment we might need to make is to the applyTransaction function.

We currently have this:

    applyTransaction :: Transaction -> Account -> Account
    applyTransaction transaction account = Account {accountAmount = newAccountAmount}
      where newAccountAmount = accountAmount account + transactionAmount transaction

which is *creating* a new Account, but what we actually want to do is *update* just the accountAmount field of the passed in account. If we change it to the following, that's exactly what we'll be doing:

    applyTransaction :: Transaction -> Account -> Account
    applyTransaction transaction account = account {accountAmount = newAccountAmount}
      where newAccountAmount = accountAmount account + transactionAmount transaction

That is, if we have a Record of data called aRecord, and we want to update the someField field of it to a new value called newValue, we can do it like this: aRecord { someField = newValue }

After we do this, adding an accountName to the Account data type should be easy as pie.

**Comment by rwobben** [comment]
IM a right that the only change is Account to account ?

**Comment by GetContented** [comment]
Yeah, and then also adding the name field to the Account data type.

**Comment by rwobben** [comment]
oke,

You mean change this : 

data Account = Account { accountBalance :: Amount }

to this : 

data Account = Account { accountBalance :: Amount, account : Account  }

**Comment by GetContented** [comment]
No, that  would be a recursive data type, which wouldn't work very well, and isn't what we want.

I'm just talking about adding a name to an account (accountName) which is a String.

By the way, be careful to write "::" and not ":".

**Comment by rwobben** [comment]
then I misunderstood you.

You mean change this : 

    applyTransaction transaction account = Account {accountBalance = newAccountBalance} 
       where newAccountBalance = accountBalance account + transactionAmount transaction 

to 

    applyTransaction transaction account(accountName)  = Account {accountBalance = newAccountBalance} 
       where newAccountBalance = accountBalance account + transactionAmount transaction 

if this is not what you mean. Can you try  to explain it one more time.

**Comment by GetContented** [comment]
We want to add a name to an account so accounts can have a name on them. To do so, we have to adjust the data type for Account. It needs to be this:

  data Account = Account { accountName :: String
                         , accountAmount :: Amount }

Sorry, I thought this was very simple to understand because you just did something very similar on another data type.

If you do that, though, then applyTransaction will stop working properly because of the way we're returning a new Account. We're creating a new Account in that function, which means it must have a value for *every* field in Account in order to work. This is too tightly bound to the shape of Account.

Instead, we could use a feature of records called *record fields updates* which lets you take a piece of data (such as our account variable in this function, which is of type Account), and create a new version with only the specified field/values updated in it.

So this is how we would change this:

    applyTransaction :: Transaction -> Account -> Account
    applyTransaction transaction account = account {accountAmount = newAccountAmount}
      where newAccountAmount = accountAmount account + transactionAmount transaction

**Comment by GetContented** [comment]
In other words, if we have this type:

    data Account = Account { accountName :: String
                           , accountAmount :: Amount }

Then this definition and expression won't work to create an Account value:

    handy =  Account {accountName = "Handy Account"}

The reason? it doesn't have all the fields specified, so it will fail. The type of the data constructor function "Account" has TWO arguments... 

However, if we have a function such as this that takes an Account value:

    addBossToAccountName :: String -> Account -> Account
    addBossToAccountName s acc = acc { accountName = accountName acc ++ " boss!" }

It will work fine, because it's just modifying acc here, not creating a new one.

Hope that's clear?

**Comment by rwobben** [comment]
Everything is clear

**Comment by GetContented** [comment]
Cool! :)
