### ISSUE TITLE
Change an Account to hold a log of transactions

### ISSUE THREAD

**Issue by GetContented** [rwobben/paytime#11]
This task can be broken into two parts.

**Part 1**
So that we can begin to keep a track of all the transaction as they happen over time, let's add a new field to Account that will be a list of transactions. We could call it accountTransactions. This should be reasonably easy for you to do by now. The only tricky part might be working out what the type should be.

**Part 2**
One we have that accountTransactions field in place, we want to make sure whenever we do a withdraw or deposit, we also add the Transaction to the log of the Account.
Where should this change go? Do you want to add the item to the beginning of the list, or the end? to add it to the end, we put the item into a list, and use this function (++) :: [a] -> [a] -> [a]. This is simple two-list list concatenation (concatenation means joining). To put it on the front, you'll need to use this function (:) :: a -> [a] -> [a] which takes a single element of any type, then a list of that type, and returns the list with the single element prepended to it (prepended means put on the front of).

It's worth noting that Haskell uses singly-linked lists, which means adding to the end, or looking at the end takes more and more time the longer the list gets, whereas adding to the front or looking at the front is immediate. You'll find out the reason if you try to recreate the functions (:) and (++) from scratch by yourself (they're recursive), or if you look them up in the source.

As an example, let's learn a bit more about String and List which you might already know, but revision doesn't hurt.

Firstly, String is simply a type alias for [Char]. We type string literals with double quotes, and Char literals with single quotes. So, this is an example of a value of type Char: 'a', but this is a String: "a".

String literal syntax with double quotes is just "syntactic sugar" for a set of chars joined with the (:) operator, joined to the empty list at the end.

So, these are all equivalent:

    'a' : ('b' : ('c' : ('d' : [])))

    'a' : 'b' : 'c' : 'd' : []

    "a" ++ "b" ++ "c" ++ "d"

    "a" ++ ("b" ++ ("c" ++ "d"))

    ("a" ++ "b") ++ ("c" ++ "d")

    (("a" ++ "b") ++ "c") ++ "d"

    ['a'] ++ ['b'] ++ ['c'] ++ ['d']

    "abcd"

    ['a','b','c','d']
    
    ['a','b'] ++ ['c','d']
    
    "abc" ++ "d"
    
    'a' : "bcd"

Note that (:) and (++) work on ANY lists, not just List of Char (ie String), so this will work just fine:

  [1,2,3] ++ [5,6,7]

**Comment by rwobben** [comment]
Yes. my first guess would be that the type of accountTransactions would be Transaction but then I think I will made a circular one.

**Comment by GetContented** [comment]
That's very close, but we want a LIST of transactions, not just a single transaction. It's not circular, because we're adding this field to Account, not Transaction.

In other words, an Account will have a list of transactions.

The type of a list of something is written like this: [Char] (is a list of Char) [String] (is a list of String), [Account] (is a list of Account). [[Account]] (is a list of lists of Account), etc.

**Comment by rwobben** [comment]
Oke, then the type of accountTransitions is [Account]

**Comment by GetContented** [comment]
Why would the type of accountTransactions be [Account]?

What does [Account] mean? It means a list of accounts, right? So, why would an account have a list of accounts inside it?

**Comment by rwobben** [comment]
Sorry. Im confused because we are working on several "bugs" now. 
The right solution is then [Transactions]

**Comment by rwobben** [comment]
Tomorrow I hope to find out how I can update the list then and updating the balance of that account. 
I think I need to use do then or ;

**Comment by GetContented** [comment]
Sorry. Perhaps, to make it easier for you, just choose one issue at a time and work on it. When I add these issues it's for the future, anyway. I don't expect you to do everything at once. I'm just adding issues and notes where relevant so you can proceed however fast you want :) Is that a good thing?

I don't understand what you meant by this: "I think I need to use do then or ;".

**Comment by rwobben** [comment]
Already solved. 
I thought I need to use a do function or a ; to make 2 functions but that was a wrong thought

**Comment by GetContented** [comment]
Um ok.. do isn't a function, it's a keyword: it's syntax.
