### ISSUE TITLE
Find out the bank balance

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#27]
I think we need a map for this 
Or a fold but that is something I did not have learned so far.

**Comment by GetContented** [comment]
Ooh cool :) hehe...

Yeah, a map and a sum would do it, or a fold.

Do you want to learn folds? It's a good excuse to learn folds, let's do it!

My method of showing folds is this: To learn folds, you need a good handle on recursion, so it's a good exercise for you to create your own versions of the map and filter functions yourself using recursion. Once you've done that, you should create a your own version of the sum function using recursion.

So, create the functions for these type signatures:

    filter' :: (a -> Bool) -> [a] -> [a]

    map' :: (a -> b) -> [a] -> [b]

    sum' :: (Num a) => [a] -> a

**Comment by GetContented** [comment]
By the way, we've designed the system in such a way that the bank balance is automatically adjusted with every transatction. 

So, this isn't technically necessary, because we could just pull the balance field out of the account.

However, I think this is a good idea for you to use this example to work more on recursion and start to learn folds.

**Comment by rwobben** [comment]
Hmm, 

Lets say we have 2 accounts  client1 with a amount of 100 and client2 with a amount of 50.

Then the system says this ; 

    Accounts raw data: fromList [("client1",Account {accountName = "client1", accountBalance = 100, accountTransaction = []}),("client2",Account {accountName = "client2", accountBalance = 50, accountTransaction = []})]

I thought the meaning of this challenge is to add 100 and 50 together. So the total of the bank is 150 and I do not see it yet. 

Or is this another misunderstanding

**Comment by GetContented** [comment]
Oh... you meant the balance of the entire bank itself?

**Comment by GetContented** [comment]
Ok, cool. Yes, this is still a good exercise then... proceed with the exercises.

**Comment by rwobben** [comment]
Yes, I mean that. I assumed that you were meaning that. I will proceed 
I also think this is a good exercise to learn and explore recursion.

**Comment by GetContented** [comment]
Yeah :) either are good :)

**Comment by rwobben** [comment]
First one is ready : 

    filter' :: (a -> Bool) -> [a] -> [a]

    filter' fun [] = [] 

    filter' fun array = filter2 fun array  [] 
                        where filter2 fun [] acc = acc 
                              filter2 fun (x:xs) acc =  if fun x then x:acc else acc

**Comment by GetContented** [comment]
You code isn't recursive, and it doesn't work when I test it on this:

    > filter' even [1..10]
    []

here's what it should do:

    > filter even [1..10]
    [2,4,6,8,10]

**Comment by rwobben** [comment]
Map is a little bit harder. 

I have this : 

   map' :: (a -> b) -> [a] -> [b]                     
          
    map' fun [] = [] 

    map' fun array = map2 fun array  [] 
                     where map2 fun [] acc = acc 
                           map2 fun (x:xs) acc = map2 fun xs item:acc
                                                 where item = fun x 

But then I see a infinitive error message.
Am I right that map2 fun xs is too blame.
That Haskell think thats xs is a argument of fun ? 

Here the actual error messages : http://lpaste.net/149082

**Comment by GetContented** [comment]
You have the right idea using a conditional, or a guard clause, though, and using (:) to prepend the item if it passes the predicate function (ie the "fun x" returns True).

**Comment by rwobben** [comment]
oke, 

A better on for filter ; 

filter' :: (a -> Bool) -> [a] -> [a]

filter' fun [] = [] 

filter' fun array = filter2 fun array  [] 
                    where filter2 fun [] acc = reverse acc 
                          filter2 fun (x:xs) acc =  if fun x then filter2 fun xs (x:acc) else filter2 fun xs acc

**Comment by rwobben** [comment]
and a working map 

    map' :: (a -> b) -> [a] -> [b] 
    map' fun [] = [] 

    map' fun array = map2 fun array  [] 
                     where map2 fun [] acc = reverse acc 
                           map2 fun (x:xs) acc = map2 fun xs (item:acc)
                                                 where item = fun x

**Comment by GetContented** [comment]
For filter you have too much code. See if you can reduce it. You should only need two lines including the empty list definition.

Also, I don't want to be rude, but please calling array list. Haskell has both, and they are very different things.

**Comment by GetContented** [comment]
Same problem with the map one. This is too much code. You only need two lines.

**Comment by GetContented** [comment]
You don't need an accumulator.

Map doesn't "do something to a list", rather it "builds you a new list".

**Comment by rwobben** [comment]
oke, then I think I know how to do it in 2 lines

**Comment by rwobben** [comment]
Here the filter : 

filter' :: (a -> Bool) -> [a] -> [a]

    filter' fun [] = [] 
    filter' fun (x:xs) =  if fun x then  x : filter' fun xs else filter' fun xs

**Comment by GetContented** [comment]
Yes! Nice work on the filter. That's perfect. Well done. This is the EXACT definition that is written in the Prelude, built into Haskell. :) Nice.

**Comment by GetContented** [comment]
Let's look at all the cases for lists of items of up to 3 items:

    map' f [] = []
    map' f [x] = f x
    map' f [y,z] = f y : f z : []
    map' f (x:y:z:[]) = f x : f y : f z : []

Notice something interesting? we could use mathematical substitution for our definition for map' f [y,z] into the end of map' f (x:y:z:[]), right? maybe if we decided to call [y,z] (which is the same as y:z:[]) "xs".

then we'd have:
    map' f (x:xs) = f x : map f xs

because x:xs matches [x] as x : [] just fine, we only need this defintion with the first one (map' f [] = []), and we're golden!

**Comment by rwobben** [comment]
Yep, the only thing I noticed is that you are calling map instead of map'  

And sum is nothing more then adding all the numbers on a list.
so mapping over the list and add all up. :)

**Comment by GetContented** [comment]
Um.... hang on haha... ignore that I made a spelling mistake! :)

I was trying to show you recursive induction by cases, but that's ok.

So.. if map' f [] = []
and we know that map' f [x] = f x : [] right?
well, another way to write this is map' (x:[]) = f x : [] right?
so, we know map' f [] = [], and we can see that this is what the END of map' (x:[]) looks like... so we can substitute map' f [] = [] into the other function as a variable, called xs. This is how we get the general case.

**Comment by GetContented** [comment]
so map' f (x:[]) = f x : map f (f x : [])
right?
and we can change [] to xs, and it becomes a general recursive function that works on ANY tail, not just a tail of []:

    map' f (x:xs) = f x : map f xs

**Comment by rwobben** [comment]
I noticed it . No big deal. 
I understand what you mean. 

Im now trying to make sum work . I thought it would be a easy one with using map
but that does not work :( 
So back to recursion :)

**Comment by rwobben** [comment]
and that worked 

    sum' :: (Num a) => [a] -> a
    sum' [] = 0 
    sum' (x:xs) = x + sum xs

**Comment by rwobben** [comment]
I hope I get a good grade now :)

**Comment by GetContented** [comment]
yes! :) Nice.

**Comment by GetContented** [comment]
haha :) yeah, you've done well!

**Comment by rwobben** [comment]
little joke

**Comment by GetContented** [comment]
yeah, I got your joke :) 

Now, implement product', and then I'll help you to see what fold is.

    product' :: Num a => [a] -> a

product takes a list of numbers, and multiplies them

**Comment by rwobben** [comment]
Easy one after sum.
It's almost the same. 

   product' :: Num a => [a] -> a
   product' [] = 1 
   product' (x:xs) = x * product' xs

**Comment by GetContented** [comment]
VERY well done. Ok... hang on one sec :)

**Comment by GetContented** [comment]
Ok, so looking at both of these functions, what can you see that's the same, and what's different?

    sum' :: Num a => [a] -> a
    sum' [] = []
    sum' (x:xs) = x + sum' xs

    product' :: Num a => [a] -> a
    product' [] = []
    product' (x:xs) = x * product' xs

**Comment by rwobben** [comment]
The only difference is that the function. First case + , second case * 
The rest is the same.

**Comment by GetContented** [comment]
Ah sorry I made an error in my code :) haha... coud you answer that again, looking at my fixed changed version?

**Comment by rwobben** [comment]
Oke, 

The difference is that one the first case the return is zero instead of 1 
Second difference is that the function is in the  first case + and on the second case * 
And of course the names are different.

The rest is all the same.

**Comment by GetContented** [comment]
Yes. Sorry for making you walk through these elementary steps. It's important though.

So, 
what is the relationship between (+) and its value 0?
and what is the relationship between (*) and its value 1?

This might be very hard, but give it a go. If you can't work it out on your own that's fine and I'll explain.

**Comment by GetContented** [comment]
It might help to consider a similar reducing function called concat function whose type is [[a]] -> [a], and whose value is []. Concat is used to join lists together.

**Comment by rwobben** [comment]
I think I have a idea.

Lets say we sum this [ 1,2,3] 
When almost everything is done it will be  1 + 2 + 3 + [] 
Because we want to know  1 + 2 + 3, [] has to be zero
so the calculation will be 1 + 2 + 3 which is 6  

The same with * 
multiply [ 1 , 2 ,3] will be 1 * 2 * 3 * [] 
if we now schould use a zero the outcome will always be zero.
and because n * 1 = n , we use here a 1 
so the calculation will be 1 * 2 * 3 * 1  which will be 6

**Comment by GetContented** [comment]
So, what's the relationship of (+) to 0 ?

**Comment by GetContented** [comment]
Or, put a different way, what does 0 mean for (+) ?

**Comment by rwobben** [comment]
now im confused. I will think about this today

**Comment by GetContented** [comment]
Let me ask you another way:

what is 1 + 0 ? what is 1 + 0 + 0 ?

what does 0 do to the value of addition sums?

**Comment by GetContented** [comment]
It's the same question as:

what does 1 do to multiplication sums? what is 5 * 1 ? what is 5 * 1 * 1 ?

What effect does multiplication by 1 have?

**Comment by rwobben** [comment]
Both do not have a effect on the outcome. 

As I said if you do n + 0 = n and n * 1 = n 
n + 0 + 0 = n and n * 1  * 1 = n 

So it do not matter how many times you it.

**Comment by GetContented** [comment]
yes! exactly.

In mathematics, and in Haskell, these values are called the identity values of their respective functions.

For  (+) and (-), the identity is 0. For (*) and (/), the identity is 1, and for (++), the identity is [].

**Comment by GetContented** [comment]
These are the "base" values that "set up the base construction of the context that the function can take place in. They're kind of like the space in which the function takes place.

Additon and subtraction take place in zero, because they're about the presence or absence of numeric value.
Multiplication and division take place in relation to one (because they're about ratios).
(++) takes place within an empty list because it's about joining lists together.

**Comment by GetContented** [comment]
So, now I'm going to ask you to create a general higher order function that has this type signature:

This does what sum, product and sum do : it takes a reducing function (such as (+)), and an identity value (such as 0), and a list (such as [1,2,3]) and returns the result of recursively applying the reducing function to successive values of the list, starting with the identity value.

so:

    sum [1,2,3] == reduce (+) 0 [1,2,3]

You can "extract" this out of the sum' function you wrote by first copying it then renaming it `reduce`, then extracting the (+) function (reducing function) as an argument to it, and then extracting the 0 value (its identity value) as an argument, and making sure you pass the reducing function back into the recursive application at the end.

**Comment by rwobben** [comment]
So I have to write the reduce function ?

**Comment by rwobben** [comment]
Got it compiling

    reduce fun start_value []     = start_value 
    reduce fun start_value (x:xs) = x `fun` (reduce fun start_value xs)

but when I want to run it , I see this error message: 

    *Main> reduce (+) [1,2,3] 

    <interactive>:30:1:
        Non type-variable argument in the constraint: Num [t]
        (Use FlexibleContexts to permit this)
        When checking that ‘it’ has the inferred type
          it :: forall t. (Num t, Num [t]) => [[t]] -> [t]

**Comment by GetContented** [comment]
Your functions are very close, but there are two little problems:

1. your type signature is a little incorrect. "fun" must be a function of two values, so this is the correct type signature (note the brackets! they're important)

    reduce :: Num a => (a -> a -> a) -> a -> [a] -> a

2. In your second definition you have the order of x and fun backwards. If you want to use fun as if it were an operator (this is called "infix notation"), you can put it in backquotes:

     reduce fun start_value (x:xs) =  x `fun`  (reduce fun start_value xs)

or, you can just put it in prefix notation, like usual function application goes:

     reduce fun start_value (x:xs) =  fun x (reduce fun start_value xs)

**Comment by GetContented** [comment]
Ah the backquotes don't seem to print properly for me for some reason.

**Comment by GetContented** [comment]
No, your code is fine. You're just applying the function incorrectly, becuse you out the identity value:

    reduce (+) 0 [1,2,3]

**Comment by GetContented** [comment]
Well done.
All that remains is that we need to generalise the type to work on ANYthing, not just numbers:

    reduce :: (a -> b -> b) -> b -> [a] -> b

Now we can try it out as concatenation:

    reduce (++) [] ["Hi! ", "How ", "are ", "you?"]
    "Hi! How are you?"

Cool :) works!

**Comment by GetContented** [comment]
Notice that if the function has a and b, that means that the "thing being reduced" can be a different type to the "thing that it gets reduced to".

Anyway, in Haskell we don't call the function you just wrote "reduce", we call it foldr!

You just wrote a right fold! Well done! Pat yourself on the back.

**Comment by GetContented** [comment]
Ok... using foldr, how can we write our own version of the sum function, rather than using recursion like we did earlier?

**Comment by GetContented** [comment]
this is the recursive version of sum, for reference:

    sum' :: Num a => [a] -> a
    sum' [] = 0
    sum' (x:xs) = x + sum' xs


Now, if we have a generalise recursive function (which we do, it's called foldr), how can we write this same sum' function, but using only foldr?

**Comment by rwobben** [comment]
Right out of my head it would be this 

 sum' :: Num a => [a] -> a 
 sum list = foldr (+) 0 list

**Comment by rwobben** [comment]
and it works :)

**Comment by GetContented** [comment]
Yep! You *can* eta-reduce this.

so sum' = foldr (+) 0

And what about product? easy, right?

    product' = foldr (*) 1

Ok, now what abuot concat? I'll give you the type signature for this one and you can do it yourself:

    concat' :: [[a]] -> [a]

Think about the types you need

**Comment by rwobben** [comment]
Hmm, 

I came up with this so far : 

   concat' :: [[a]] -> [a]
   concat' list = foldr (:) list 

but this code does not work with the type defenition that you provided.

**Comment by GetContented** [comment]
yeah that won't work... foldr (:) [] will just rebuild the same list, because it just takes items and prepends them to an empty list.

**Comment by GetContented** [comment]
It will probably help to think about what concat is doing.

It takes a list of lists, and glues them into one single list.

It's the same pattern as sum, because sum takes a list of numbers, and glues them into a single number using (+) to glue successive numbers into the accumuliating value.

    foldr (+) 0 [1,2,3,4,5,6] 

is equal to 

    1 + (2 + (3 + (4 + (5+ (6 + 0)))))

So, what 2-argument function do we know of that takes a list, and another list, and joins them into one single list? and what would its identity value be?

**Comment by rwobben** [comment]
Hmm, 
You mean to make a function that takes for example this [ [ 1,2,3] ] and returns this [1,2,3] 
Then I have to think good how to deal with it

**Comment by GetContented** [comment]
concat [[1,2,3,4,5],[1,2,3,4,5],[5,4,4]]

equals

    [1,2,3,4,5,1,2,3,4,5,5,4,4]

**Comment by GetContented** [comment]
It's the exact same pattern as sum and product, but with a different binary function (binary function means 2-argument function), and a different identity value.

If you don't know which function has the form [a] -> [a] -> [a] you can hoogle it, and it will show you some suggestions.

foldr takes the  first and second items of the list, and applies the folding function to them... then it takes THAT result, and the third item on the list, and applies the folding function to THEM, and it keeps doing that until it hits the empty list, at which point it uses the identity value, and the result of the whole folding function is that answer.

**Comment by GetContented** [comment]
So for this:

    concat [[1,2,3,4,5],[1,2,3,4,5],[5,4,4]]

the foldr we're after would do this:

    [1,2,3,4,5] ??fun ([1,2,3,4,5] ??fun ([5,4,4] ??fun ??ident-value))

which would evalute to:

    [1,2,3,4,5,1,2,3,4,5,5,4,4]

but what is "??fun", and what is "??ident-value". We know ??fun will be a function of two arguments of some kind... and we can work out what the types of those arguments will be, because it'll be the same type as the ??ident-value. We know the type of the ??ident-value, because it has to be the same type as the answer, which is [1,2,3,4,5,1,2,3,4,5,5,4,4], right? and from the type definiton of concat that this type is generally [a].

Can we work out what function when passed [a] and [a] returns [a] ?

**Comment by rwobben** [comment]
I did hoogle it and the first one was ++.
I will try it later on the day. have to go to swimming lessons with my daugther

**Comment by GetContented** [comment]
Cool :) have a think about (++) and what it does and how it relates to what concat does.

**Comment by GetContented** [comment]
... and whether it's a similar relationship to (+) and sum, or (*) and product.

**Comment by rwobben** [comment]
Solved it also.
With a new fresh look I came to this solution: 

    concat' :: [[a]] -> [a]
    concat' list = foldr (++) [] list

**Comment by rwobben** [comment]
I m maybe a little fast but what if you want to sum up this : 

[ {type: number, value: 1} , {type: number value: 2} ] 

This is maybe not valid haskell but you get the idea what I mean.

**Comment by GetContented** [comment]
your implementation of concat' can be eta-reduced to 

      concat' = foldr (++) [] 

but otherwise well done :)

**Comment by GetContented** [comment]
Ok so what if you want to add up all the balances in a list of accounts?

    sumAccounts :: [Account] -> Integer

You can't just use foldr with (+) and 0, can you... you need some function of type (a -> b -> b)... the b will be Integer because of the return type of sumAccounts, but the a type will need to be Account... so the "folding function" needs to have type Account -> Integer -> Integer. And because we're adding, we know the identity function needs to be 0.

So... finish writing this function, by replacing the "..." with the rest of the function:

    sumAccounts :: [Account] -> Integer
    sumAccounts = foldr f 0
      where f account acc = acc + ...

**Comment by GetContented** [comment]
(It should sum the balances of all the accounts in the list of accounts).

Once we've done this, we can think about how to do it with a Map.

**Comment by rwobben** [comment]
I suspect it will be Accountbalance account. 
I will try it as soon as I have figured out how the list would look like. 
I think I can find it on earlier PR. 
IM begin to feel tired.

**Comment by rwobben** [comment]
Did a last attempt today
I have this code :  

    sumAccounts :: [Account] -> Integer
    sumAccounts = foldr f 0
      where f account acc = acc + accountBalance account

it compiles well but as soon as I want to test it with 

   sumAccounts [ {accountName = "test", accountBalance = 100, accountTransaction = []} ] 

I see this error message ; 

    parse error on input ‘{’

**Comment by rwobben** [comment]
Got it working.

    sumAccounts [Account {accountName = "test", accountBalance = 100, accountTransaction = []},   Account {accountName="test2", accountBalance = 50, accountTransaction = []}  ] 
    150

**Comment by GetContented** [comment]
Cool :) yeah, you just left off the value constructor "Account" in the first case, obviously). Cool.

So, now you know how to do right-folding. Do you want to finish this task off now, or shall we look at left folding, too?

**Comment by rwobben** [comment]
I have no problem looking at left-folding.

**Comment by GetContented** [comment]
Ok.

    sum [1,2,3]

end up being evaluated as this:

    1 + (2 + (3 + 0))

...which is called right-associativity. This means the things to the right are evaluated first. 

That's why foldr is called foldr, because it's right-associative.

Addition doesn't care what order things are done in, (3 + (2 + 1)) is the same as ((3 + 2) + 1) so it doesn't matter much for addition. Same with multiplication. However, there are *some* binary operations where it does matter quite a lot.

foldl is the name of the haskell function that does a left-associative fold.

foldr puts the recursion on the right. foldl puts the recursion on the left.

Sometimes this has interesting ramifications.

It's a good idea to read these:

http://stackoverflow.com/questions/384797/implications-of-foldr-vs-foldl-or-foldl
https://wiki.haskell.org/Foldr_Foldl_Foldl'

**Comment by rwobben** [comment]
I read both pages very quick but your right . Using foldl can give wierd outcome as you use it wrong.
The last article was very clear with saying to use foldr for conversions and use foldl' for calculations expecially for big lists.

So I think we can better use foldl' for solving our problem. Agreed ?

**Comment by rwobben** [comment]
I thought about solving our problem.
I think we have to adjust the code so it works with the value of a item.
I noticed that map is working as a key/value store. 
And in the value the balance can be found.

**Comment by GetContented** [comment]
foldr works fine for most things. Unless you're going to have something with more than 1000 items, it doesn't make much difference.

you can use a foldr on maps just fine because the REAL type signature of foldr doesn't actually use List, it uses Foldable t:

    foldr :: Foldable t => (a -> b -> b) -> b -> t a -> b

and, Map is an instance of Foldable, so it will work like this:

    foldr :: (a -> b -> b) -> b -> Map k a -> b

so ,really, you just need to write a folding function that takes a map and an Integer, and returns an Integer, using (+).

**Comment by rwobben** [comment]
oke, and the Account is the value. So I have to find a way to get the value out of the Map. Right ?

**Comment by GetContented** [comment]
No.

Map is an instance of Foldable. That means you can use foldr on it, because foldr knows how to work with ANY type that implements it. That means the implementors of Map implemented foldr on it.

So all you have to do is write a function that has the type (a -> b -> b) where "a" is the type of the value type of map... for us, using Map String Account as Map k a, the value type is Account. Because we're writing a function that adds Integers, the return type is Integer. That's the "b" type of the function.

So, you need a function to pass to foldr that has this type: (Account -> Integer -> Integer)

That is, this function takes an Account, and an Integer, and takes the balance out of the account and adds it to the integer and that's what it returns.

Imagine we had a type:

    data Yay = Yay Integer
    type Fun = Map String Yay

and we had a Map of String Yay, which is a Fun:

    this :: Fun
    this = fromList [("one", Yay 3), ("two", Yay 8), ("something else", Yay9)]

and we wanted to add them using foldr... how would we do that? 

    theSum :: Integer
    thesSum = foldr addYayToInteger 0 this

    addYayToInteger :: Yay -> Integer -> Integer
    addYayToInteger (Yay num) num2 = num + num2

Right?

Now, given that we are using a record type to store Account, and so we don't need to use pattern matching like this, can you write that function for the Account map foldr?

**Comment by rwobben** [comment]
Sorry, till now no luck. 

I change the code to this : 

sumAccounts :: [Account] -> Integer
sumAccounts = foldr f 0
  where f (accountBalance account) acc = acc + account

but then I see a parse error on Parse error in pattern: accountBalance

and when I use the code that worked on a list I also see a lot of errors.

**Comment by GetContented** [comment]
You're trying to apply a function in the arguments section (ie on the left of the equals sign). You can't do that. All you can do on the left of the equals sign is pattern match arguments.

In other words, this makes no sense and is NOT a proper function definition:

    f (accountBalance account) acc = acc + account

**Comment by rwobben** [comment]
oke, 

And 

   f account  = acc + accountBalance  account 

does also not work

**Comment by GetContented** [comment]
Rememeber it needs to be a function of two arguments, not one. What you just posted is a function of one argument.

**Comment by GetContented** [comment]
The function's type signature is f :: Account -> Integer -> Integer

**Comment by rwobben** [comment]
oke

I have now this : 

    sumAccounts :: Account -> Integer -> Integer
    sumAccounts = foldr f 0
      where f account acc = acc + accountBalance account 

Where I have this error messages :  http://lpaste.net/149540

The second one I understand accountBalance account gives a Amount not a Integer 
The first one I do not understand what it means.

**Comment by GetContented** [comment]
I'm not sure what function you're trying to write... the folding function, or the entire fold... 

sumAccounts sounds like it's the whole fold... as in... this function should take an Accounts, and given a single Integer...

So if that's the case, your type signature is wrong.

The type signature I gave you was for the folding function (what you're calling f here).

THIS is how the entire function's signature should look:

    sumAccounts :: AccountsStore -> Integer
    sumAccounts = foldr f 0
      where f x n = n + accountBalance x

**Comment by rwobben** [comment]
Thanks, 

Now the next problem. Can we add it to our main function,
As far as I understand that one needs a AccountStore and returns a AccountStore.
This function needs a AccountStore and returns a integer.

**Comment by GetContented** [comment]
Which function is the main function you're talking about? What's its name?

**Comment by rwobben** [comment]
The main function which displays the menu. On my project it can be found at app/main.hs

**Comment by GetContented** [comment]
I'm not sure what your question is. Do you not know how to add a pattern clause to the menu case expression?

Or are you asking me how you would write an expression that the menu delegates to?

**Comment by GetContented** [comment]
To add another menu item, adjust the menu item string (the one that prints the message to the user saying what they can type)... such as BB: Bank Balance.

Then, add that clause to the menu case:

    "BB"   -> do
               doShowBankBalance accounts
               runLoop newAccounts

but comment it out until you've written the doShowBankBalance function, whose type should be AccountStore -> IO ()

**Comment by GetContented** [comment]
... and (hopefully) obviously, the doShowBankBalance function will use the one we just finished writing that does the fold on the AccountStore. It should also be in a do block, and it needs to either finish with a printStrLn, or return () (because of its type).

**Comment by rwobben** [comment]
Yep, I did that already  I think I was getting error messages because I had the types wrong.
There is a new PR on the way for this.

**Comment by rwobben** [comment]
Solved by #28
