### ISSUE TITLE
make checks on some accounts

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#3]
We have make some checks because accounts like "cash on hand" cannot be negative. 
Right now it possible to make the account negative.

**Comment by GetContented** [comment]
I've thought about this a bit. What behaviour do you want if we try to debit below 0? Do you want the withdraw to just not do anything? or something else?

**Comment by rwobben** [comment]
I think the best is to give a sort of error messages and let the account unchanged.

**Comment by GetContented** [comment]
Well, there is a type called Maybe which is the most basic kind of erroring in Haskell. We could use that, it will involve beginning to understand algebraic data types.

**Comment by rwobben** [comment]
oke, I will hits the books

**Comment by GetContented** [comment]
You've actually been using algebraic data types all along. `Account` is an example of one. It's a product type. The only difference is Maybe is a type constructor, which means you need to give it a type before it can be a concrete type.

Maybe looks like this:

    data Maybe a = Just a | Nothing

If we want  to make a value of either a String, or nothing at all, we can use it like this:

    aString :: Maybe String
    aString = Just "Hi"

    noString :: Maybe String
    noString = Nothing

So, the withdraw function changes to return a Maybe Account. If it fails, we return Nothing. If it succeeds, we return a Just wrappering the account.

**Comment by rwobben** [comment]
it makes sense but if we return nothing does the account still have the old value ?

**Comment by GetContented** [comment]
Haskell doesn't use mutable values, so it depends how we store it.

But, yes, whatever piece of code is updating our value could look at the return type, and if it's Nothing, return the existing Account. If it's a Just value, then return that value from within the Just.

**Comment by rwobben** [comment]
Oke, if we do that im happy.  
But first we have to find out how we can multiple accounts which are not hardwired in the code.
We are discussing this in another topic
