### ISSUE TITLE
Refractor the io stuff out of the pure functions 

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#32]
I think the next step will be to refractor the io-stuff out of the pure functions stuff.
And we have to think about how we can make it work that the display functions do not use data-structures but functions to pass the right arguments to print. 

Shall we begin with the DoCreate function ?

**Comment by GetContented** [comment]
You should be able to do the whole separation in one go.

**Comment by GetContented** [comment]
But yeah, proceed as you like. Far be it for me to deny you going in smaller steps :)

**Comment by rwobben** [comment]
I think there is a communication problem.
I thougt we try to seperate the io-stuff out of CreateAccounts. 
Or do yoiu mean put CreateAccounts in one file because there is io stuff in it 
and put the other files we need for creating a acccount in another file because they seem pure to me.

**Comment by GetContented** [comment]
I don't know "separate the IO-stuff out of createAccounts" means. Could you explain that?

**Comment by rwobben** [comment]
oke, 
Then we can do it on one go. 

I had this idea :+1: 

src 
-- main.hs 
-- types.hs  (for all the types and data every module uses)
----   accounts 
----  LIb.hs (all the pure functions)
---   cli.hs ( all the input for the cli) 
---   Transactions
-----   Lib.hs (allthe pure functions) 
-----  cli.hs ( all the input for the cl) 

What do you think about that ?

**Comment by GetContented** [comment]
You can do it however you like it. Personally I'd find it tiresome changing between all those files, but if you like having one or two functions per Module, go for it.

Also, it'll be pretty annoying looking up your types in a separate file to the functions that work with them. I really don't recommend doing that.

But, like I've said a lot of times before, *YOU* need to do this stuff so can make your own mistakes. It's not going to help having me preventing you from making mistakes.

**Comment by GetContented** [comment]
Just notice if we make this change and you spend a lot of time flipping between files then something is probably wrong. Putting things in modules should make it easier to read and write code, not the other way around.

**Comment by rwobben** [comment]
Oke, 

I thought to make for all the types a seperate file because they are needed on all and if you put them on all files there is a lot of duplicate and more places where we have to change them.

I will try to make this work.

**Comment by GetContented** [comment]
Usually you'd put the types in the innermost portion. This is usually the pure functions. You don't export the types directly, but rather have functons that can create the types (the make functions) that you import into other modules that use them.

This is called programming to an interface.

Notice, for example, how you import Data.Map. You have to import the type AND the functions that use it from the one file, not separate files. You never import its internal types or internal functions.

**Comment by rwobben** [comment]
So. its not good to make a file named Types.hs and import it with  import Types.
I did that a few minutes ago and that worked and compiled well. 

if not, can you explain in detail how to do it the right way ?

**Comment by GetContented** [comment]
No, that's fine. You do it the way you want to. We'll see how it turns out! :)

**Comment by rwobben** [comment]
oke, 

I have done everything for the accounts except the table output. 
Any idea how we can make it work so that the functions is called correctly. 
Now I use a array of two tuples [ (name, balance)]  
And I know that you are not happy with it.

**Comment by GetContented** [comment]
I can't see your code, so I'm not sure what you're talking about.

**Comment by GetContented** [comment]
That's a List, not an Array.
This is array: https://hackage.haskell.org/package/array-0.5.1.0/docs/Data-Array.html

A List of pairs is called an association list, usually. It's very slow compared to a Map. You can use whatever you like.

**Comment by rwobben** [comment]
make a PR which I try to explain things. See #33
